databases:
  - name: pleasanter_db
    plan: basic-256mb
    region: singapore
    databaseName: pleasanter
    user: pleasanter

services:
  - type: web
    name: pleasanter
    plan: free
    runtime: image
    image:
      url: implem/pleasanter
    region: singapore
