databases:
  - name: pleasanter_db
    plan: basic-256mb
    region: singapore
    databaseName: pleasanter
    user: pleasanter

services:
  - type: web
    name: pleasanter-init
    plan: free
    runtime: image
    image:
      url: postgres:15
    region: singapore
    envVars:
      - key: PGHOST
        fromDatabase:
          name: pleasanter_db
          property: host
      - key: PGPORT
        fromDatabase:
          name: pleasanter_db
          property: port
      - key: PGUSER
        fromDatabase:
          name: pleasanter_db
          property: user
      - key: PGPASSWORD
        fromDatabase:
          name: pleasanter_db
          property: password
      - key: PGDATABASE
        fromDatabase:
          name: pleasanter_db
          property: database
    startCommand: |
      echo "Configuring database roles and permissions..."

      cat > /tmp/init_roles.sql << 'EOF'
      DO $$
      BEGIN
        IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = 'Implem.Pleasanter_Owner') THEN
          CREATE ROLE "Implem.Pleasanter_Owner" WITH LOGIN PASSWORD 'pleasanterowner';
        END IF;
        
        IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = 'Implem.Pleasanter_User') THEN
          CREATE ROLE "Implem.Pleasanter_User" WITH LOGIN PASSWORD 'pleasanteruser';
        END IF;
        
        GRANT "Implem.Pleasanter_Owner" TO pleasanter;
        GRANT "Implem.Pleasanter_User" TO pleasanter;
        
        GRANT SET ROLE "Implem.Pleasanter_Owner" TO pleasanter;
        GRANT SET ROLE "Implem.Pleasanter_User" TO pleasanter;
      END
      $$;
      EOF

      psql -f /tmp/init_roles.sql

      echo "Database roles and permissions configured successfully"

  - type: web
    name: pleasanter
    plan: free
    runtime: image
    image:
      url: implem/pleasanter
    region: singapore
    envVars:
      - key: POSTGRES_HOST
        fromDatabase:
          name: pleasanter_db
          property: host
      - key: POSTGRES_PORT
        fromDatabase:
          name: pleasanter_db
          property: port
      - key: POSTGRES_USER
        fromDatabase:
          name: pleasanter_db
          property: user
      - key: POSTGRES_PASSWORD
        fromDatabase:
          name: pleasanter_db
          property: password
      - key: POSTGRES_DB
        fromDatabase:
          name: pleasanter_db
          property: database
    startCommand: |
      export Implem.Pleasanter_Rds_PostgreSQL_SaConnectionString="Server=${POSTGRES_HOST};Port=${POSTGRES_PORT};Database=${POSTGRES_DB};UID=${POSTGRES_USER};PWD=${POSTGRES_PASSWORD};SslMode=Require;"
      export Implem.Pleasanter_Rds_PostgreSQL_OwnerConnectionString="Server=${POSTGRES_HOST};Port=${POSTGRES_PORT};Database=${POSTGRES_DB};UID=${POSTGRES_USER};PWD=${POSTGRES_PASSWORD};SslMode=Require;"
      export Implem.Pleasanter_Rds_PostgreSQL_UserConnectionString="Server=${POSTGRES_HOST};Port=${POSTGRES_PORT};Database=${POSTGRES_DB};UID=${POSTGRES_USER};PWD=${POSTGRES_PASSWORD};SslMode=Require;"
